name: Package Release

on:
  pull_request:
  push:
    branches:
      - main

permissions: write-all

jobs:
  # build_main:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  # Steps for building and testing main releases
  # Trigger deployment to production environment

  release_package:
    # if: github.ref == 'refs/heads/beta'
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.1.1
          tag_format: v${version}-b${{ github.run_id }}.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


