name: Package Release

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  # build_main:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  # Steps for building and testing main releases
  # Trigger deployment to production environment

  release_package:
    # if: github.ref == 'refs/heads/beta'
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        id: version
        run: |
          echo "v${version}-b${{ GITHUB_RUN_ID }}.${{ GITHUB_RUN_NUMBER }}"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.1.1
          dry_run: true
          tag_format: v${version}-b${{ vars.GITHUB_RUN_ID }}.${{ vars.GITHUB_RUN_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


